name: cancelable_stream
description: A stream wrapper that supports explicit cancellation of the upstream source.
repository: https://github.com/tomwyr/cancelable_stream
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
